name: income-estimator-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  
  # Core scientific computing
  - numpy>=1.24.0
  - pandas>=2.1.0
  - scikit-learn>=1.3.0
  
  # Web framework
  - fastapi>=0.104.0
  - uvicorn>=0.24.0
  
  # ML and optimization
  - xgboost>=2.0.0
  - optuna>=3.4.0
  
  # Data visualization (for notebooks)
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.17.0
  
  # Jupyter environment
  - jupyter>=1.0.0
  - notebook>=7.0.0
  - ipykernel
  
  # Development tools
  - pytest>=7.4.0
  - black>=23.9.0
  - isort>=5.12.0
  - flake8>=6.1.0
  - mypy>=1.6.0
  
  # Additional dependencies via pip
  - pip:
    - pydantic>=2.5.0
    - mlflow>=2.8.0
    - prometheus-client>=0.19.0
    - python-multipart>=0.0.6
    - python-dotenv>=1.0.0
    - click>=8.1.0
    - rich>=13.7.0
    - loguru>=0.7.0
    - joblib>=1.3.0
    - httpx>=0.25.0
    - pytest-cov>=4.1.0
    - pytest-asyncio>=0.21.0
    - pre-commit>=3.5.0
    - grafana-api>=1.0.3
    - -e .
